### ISSUE TITLE
libxml2-dev cannot be installed

### ISSUE THREAD

**Issue by torbjorn** [rocker-org/r-devel#1]
Trying to install libxml2-dev (necessary for devtools), I get the following error:

    # apt install libxml2-dev
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     libxml2-dev : Depends: libxml2 (= 2.9.14+dfsg-1.3+b3) but 2.12.7+dfsg-3+b1 is to be installed
    E: Unable to correct problems, you have held broken packages.

**Comment by torbjorn** [comment]
How about preinstalling the older version of libxml2, (it seems the updated dev package is not availbale). Then at least the devtools package would install, which would allow this image to be used for package testing

**Comment by eddelbuettel** [comment]
Thanks for trying rocker.  Now, this container (like some others) is based on Debian testing, a "rolling" distribution.  So these things can happen at times between 'testing' and 'unstable'.  The common fix is a usual Debian trick of then allowing unstable for the one operation you need at this point in time.  It will sort itself out.

#### repro

```sh
root@ce9b3e9ba1da:/# apt install libxml2-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libxml2-dev : Depends: libxml2 (= 2.9.14+dfsg-1.3+b3) but 2.12.7+dfsg-3+b1 is to be installed
E: Unable to correct problems, you have held broken packages.
root@ce9b3e9ba1da:/#
```

#### fix

```sh
root@ce9b3e9ba1da:/# apt install -t unstable libxml2-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  g++-13 g++-13-x86-64-linux-gnu gfortran-13 gfortran-13-x86-64-linux-gnu libgfortran-13-dev libstdc++-13-dev pkg-config
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  libxml2-dev
0 upgraded, 1 newly installed, 0 to remove and 32 not upgraded.
Need to get 145 kB of archives.
After this operation, 530 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian sid/main amd64 libxml2-dev amd64 2.12.7+dfsg-3+b1 [145 kB]
Fetched 145 kB in 0s (657 kB/s)     
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libxml2-dev:amd64.
(Reading database ... 179915 files and directories currently installed.)
Preparing to unpack .../libxml2-dev_2.12.7+dfsg-3+b1_amd64.deb ...
Unpacking libxml2-dev:amd64 (2.12.7+dfsg-3+b1) ...
Setting up libxml2-dev:amd64 (2.12.7+dfsg-3+b1) ...
Processing triggers for man-db (2.13.0-1) ...
root@ce9b3e9ba1da:/# 
```

**Comment by torbjorn** [comment]
Thanks.

Would it make sense to have libxml2-dev preinstalled in the image?

**Comment by eddelbuettel** [comment]
No, this has come up numerous times for numerous images here.  With maybe 50k source packages in the distribution, and an unknown number of users of these containers, we cannot really please all permutations of preferred deployments.  So we aim to provide _well-rounded yet minimal_ solutions.  It remains pretty easy and feasible for others to just take our containers as starting points and customize with preferred applications on top of them.  We do that too!

**Comment by torbjorn** [comment]
right, thanks
